package ua.raif.tgbotservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;


@DynamoDBTable(tableName = "UsersTelegram")
public class UsersTelegram {

    private String phoneNumber;

    private String userName;

    private Long userId;

    private Boolean isVerified;

    @Id
    private String id;

    @DynamoDBHashKey(attributeName = "PK")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

//    @DynamoDBRangeKey(attributeName = "SK")
//    public String getSk() {
//        return "STATIC_DATA";
//    }

    @DynamoDBAttribute(attributeName = "phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @DynamoDBAttribute(attributeName = "userName")
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @DynamoDBAttribute(attributeName = "userId")
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute(attributeName = "isVerified")
    public Boolean getVerified() {
        return isVerified;
    }

    public void setVerified(Boolean verified) {
        isVerified = verified;
    }
}
